# ============ language model configurations ============ 
OPENAI_API_KEY="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"
OPENAI_API_TYPE="openai"
BRAVE_API_KEY= "BSATN30xyj0UK6M4vQfxV7nSQDRMn0o"